---
# tasks file for webserver

- name: "Install WebServer"
  package:
          name: "{{pkg}}"
          state: present

- name: "copy webs"
  copy:
          dest: "/var/www/html/index.html"
          content: "this is webs from IP {{ansible_default_ipv4['address']}}"

- name: "starting webs"
  service:
          name: "{{pkg}}"
          state: started

